#!/usr/bin/env groovy

pipeline {
    agent any
    stages {
        stage('Initialise') {
            steps {
		      sh 'rm -rf Build-Jenkins-AMI_and_EC2'
              	      sh 'git clone https://github.com/dswilkinson73/Build-Jenkins-AMI_and_EC2.git'
		      echo "Initialising job - cloning repo"
                      dir("Build-Jenkins-AMI_and_EC2/Step1_Build-Jenkins-AMI") {
                      sh 'pwd'
                  }
            }
        }
        stage('Validate') {
            steps {
                      dir("Build-Jenkins-AMI_and_EC2/Step1_Build-Jenkins-AMI") {
                      echo "Validating PACKER json..."
                      sh 'packer validate dsw_jenkins_ami.json'
                  }
		      
            }
        }
        stage('Deploy') {
            steps {
                     dir("Build-Jenkins-AMI_and_EC2/Step1_Build-Jenkins-AMI") {
                     echo "Deploying AMI to AWS..."
                     sh 'packer build dsw_jenkins_ami.json'
                }
            }
        }
    }
}
